### PR TITLE
Don't store the metagenotype display name in extensions

### PR DESCRIPTION
**Pull request by kimrutherford**
This PR changes the code to:
  - not store the rangeDisplayName for metagenotypes in extensions
  - fill in the rangeDisplayName for metagenotypes in extensions when annotation details are requested from the server
     - the Metagenotype ID in the the rangeValue field of the extensions is used to look up the metagenotype as needed

### CODE REVIEW

**Review by jseager7 — CHANGES_REQUESTED** [review]
@kimrutherford The changes to the user interface seem to work fine for me on my local copy. I've tested renaming a metagenotype both in existing sessions and in new sessions and I can't see any problems there.

The only problem is that the metagenotype names aren't updated in the JSON export, so the code probably needs changing there to mirror the changes in `Utils.pm`. For example, I renamed the allele in the following JSON from `lasI+` to `lasI_test`:

```json
"P33883:11fa7733063e791c-3" : {
    "allele_type" : "wild_type",
    "gene" : "Pseudomonas aeruginosa P33883",
    "name" : "lasI_test",
    "primary_identifier" : "P33883:11fa7733063e791c-3",
    "synonyms" : []
},
```
But in the exported annotation extensions, it still has the old name:
```json
{
    "rangeDisplayName" : "lasI+[WT product] Pseudomonas aeruginosa (PA14) / wild type Caenorhabditis elegans (N2)",
    "rangeType" : "Metagenotype",
    "rangeValue" : "11fa7733063e791c-metagenotype-20",
    "relation" : "compared_to_control"
}
```

- - -

With regards to the potential performance issue mentioned in https://github.com/pombase/canto/issues/2505#issuecomment-1092492826, I tested the page load time on a session with 76 annotations and it seemed to load _faster_ than before, compared to commit 13cbc4d6d91efaf15e60d49cd2c4b13a1204b639 on the `master` branch: loading the page before the changes takes on average about 13 seconds, whereas after the changes it averages about 8 seconds.

I only tested using the debugging tools in Firefox, so I don't know how reliable these numbers really are. It's possible that some other code change could be accounting for the speed-up.

**Comment by kimrutherford** [comment]
> The only problem is that the metagenotype names aren't updated in the JSON export

Hi James.

Do you know if the metagenotype display name will be used downstream?  If not then the quickest fix is to remove rangeDisplayName from the JSON output.  All of the metagenotype details are encoded in the genotype and allele details elsewhere in the JSON.  If the JSON file is loaded into a database with a normalised schema perhaps including the metagenotype display name is duplication?

**Comment by jseager7** [comment]
> Do you know if the metagenotype display name will be used downstream?

Unfortunately, I suspect it is being used by one of our collaborators, purely for the sake of convenience. I agree it's redundant, but it could be a real pain to expect them to change their parsing to generate the display names dynamically. They're using a JSON database, so perhaps normalisation is less of an issue.

I'm happy to have a go at making the metagenotype display name appear correctly; I assume that the only code that would need changing is the `json` subroutine in `Serialise.pm`. Otherwise, we could just remove the display name and I can patch it back in afterwards with a script.

**Comment by kimrutherford** [comment]
OK, no problem.  I was half was through implementing the fix when I thought to ask the question.

**Comment by kimrutherford** [comment]
I've made those changes.  Could you give it a test when you get a chance?

**Review by jseager7 — APPROVED** [review]

**Comment by jseager7** [comment]
Seems like the metagenotype display names export correctly now. Thanks very much for your help. I'll merge this now.
```json
{
   "rangeDisplayName" : "lasI_test(wild type)[WT level] Pseudomonas aeruginosa (PA14) / wild type Mus musculus (BALB/c)",
   "rangeType" : "Metagenotype",
   "rangeValue" : "11fa7733063e791c-metagenotype-24",
   "relation" : "compared_to_control"
}
```

**Pull request merged**
