### PR TITLE
Add PHI-Canto documentation pages and images

### PR DESCRIPTION
**Pull request by jseager7**
Related: #1417 

This pull request adds documentation specific to PHI-base. The documents were previously stored as Google Docs; they've been downloaded as Markdown using an add-on and converted to MHTML with scripting. So far two pages are done. I'll update this PR as more pages are finished, unless we merge before then.

### Progress 

- [x] Getting started (index page)
- [x] Creating alleles and genotypes
- [ ] Curating phenotypes

### CODE REVIEW

**Comment by jseager7** [comment]
@kimrutherford I made some changes to the `.screenshot` selector in `styles.css` to set a max-width on our images, since I decided not to scale down the images manually with thumbnails.

See here: https://github.com/pombase/canto/pull/2286/commits/2fffbd62d3be8812800aaad7d8beeac73d82a949#diff-eeabeec674069e72e8e638ad22871b98R1429-R1430

However, the changes to the selector will affect your docs for PomBase as well, so I think this rule should really be restricted to the PHI-base documentation, maybe by setting another class on the top-most `<div>` for our pages:

```html
<div class="docs phi-base-docs">
```
I'm open to any other suggestions. Now that I've found an image processing library for Python (which I'm using to build the docs), it wouldn't be much effort to generate scaled versions of the images.

**Comment by kimrutherford** [comment]
> class="docs phi-base-docs"

That sounds like a good fix.  You can add the class to every doc page by editing
`root/phi_base_docs/autohandler`:

```diff
diff --git root/phi_base_docs/autohandler root/phi_base_docs/autohandler
index 8d67f58cc..51253848d 100644
--- root/phi_base_docs/autohandler
+++ root/phi_base_docs/autohandler
@@ -43,7 +43,7 @@ $hide_header => 0
   </div>
 % }
       <div class="clearall"></div>
-      <div class="docs">
+      <div class="docs phi-base-docs">
 % $m->call_next;
       </div>
     </div>
```

I checked the pombe docs with your changes and everything else looks fine.

**Comment by jseager7** [comment]
Thanks for the suggestion about using the autohandler. I hadn't considered it because I got confused by the fact that `index.mhtml` already has a `<div class="docs">` near the start of the file. I guess this is an accident?

https://github.com/pombase/canto/blob/b1c7b9c4a947f359ad750a967fef888ec242e695/root/docs/index.mhtml#L1-L9

**Comment by kimrutherford** [comment]
> I guess this is an accident?

Yep.  :-)

I had a look and it's currently
```html
<div class="docs">
   <div class="docs">
...
```
That's a bit unnecessary.

I think the class in index.mhtml can be safely removed.

**Comment by jseager7** [comment]
@kimrutherford I've made the changes to restrict the screenshot styling to PHI-Canto. I've left the extra bottom margin on all the screenshots for now, since I think it benefits all the documentation. If everything looks okay in single organism mode, then I think we should just merge these two pages, and I'll add the phenotype documentation in a separate commit when that's done.

**Comment by kimrutherford** [comment]
> If everything looks okay in single organism mode, then I think we should just merge this pull request, 

Yep!  It all looks good for pombe.

**Pull request merged**
