### PR TITLE
Add a /view_genes_and_strains route and template

### PR DESCRIPTION
**Pull request by kimrutherford**
Refs pombase/canto#2325

### CODE REVIEW

**Comment by jseager7** [comment]
Thanks for all your help. Seems like the read-only mode for the page has everything I need, so I'll look at fixing the user interface.

**Comment by jseager7** [comment]
@kimrutherford I've made the changes to the user interface so that when in read-only mode, the editing controls are hidden, the link to the edit_genes page is disabled, and the summary page link goes to the read-only version of the summary page.

Note that I haven't made any changes to the AngularJS controllers to prevent edit actions when the session is read-only: I'm relying on `ng-if` directives in the template to prevent any of that code being triggered in the first place. Is that your preferred approach, or would you like guards in the controllers as well?

- - -
read_only_organism_page

**Comment by jseager7** [comment]
While testing, I noticed that there's another page (or route), called confirm_genes, that uses the edit_organisms directives. The user is sent to this page after adding genes or organisms on the edit_genes page. So with the addition of view_genes_and_strains, we now seem to have three different versions of what is effectively the same page.

As briefly discussed in https://github.com/pombase/canto/issues/2325#issuecomment-724388795, it would be nice if we could decide on a more generic name for this page that isn't dependent on the state of the curation session.

**Review by jseager7 — APPROVED** [review]

**Comment by jseager7** [comment]
@kimrutherford Is there anything left to do before merging this? All the interface changes to the Genes and Organisms page are done, and I've fixed the somewhat-related issue of an incorrect link to the confirm_genes URL in commit https://github.com/pombase/canto/commit/5e548854a40476e31f926a0f1efb907f723977b7.

**Comment by kimrutherford** [comment]
Thanks James.  I did a bit more testing and found that the new route wasn't working correctly in non-PHI mode.  It was redirecting to the front page.  I've fixed that and now I think it's ready to go.

**Pull request merged**
