### PR TITLE
Enable configuration of experimental conditions help text

### PR DESCRIPTION
**Pull request by jseager7**
(References #2299)

@kimrutherford Here's the changes that we made to allow configuration of the help text above the experimental conditions picker. I was planning to commit this straight away, but I was wondering if you wanted to move the default help text into `canto.yaml` rather than having it in the Mason template.

### CODE REVIEW

**Comment by jseager7** [comment]
Forgot to mention that I've tested the configured help text locally and it all works fine.

**Comment by kimrutherford** [comment]
> but I was wondering if you wanted to move the default help text into canto.yaml

Yep, that makes sense.  Are you happy to have a go at that?

**Comment by jseager7** [comment]
> Yep, that makes sense. Are you happy to have a go at that?

I am, but unless you want to make this change regardless of what happens here, it might be better to wait, because the child issue for this PR (#2299) is in flux at the moment and I'm not sure if we'll end up making the changes here after all.

**Comment by kimrutherford** [comment]
> but unless you want to make this change regardless of what happens here, it might be better to wait

**Comment by kimrutherford** [comment]
> but unless you want to make this change regardless of what happens here, it might be better to wait

There's no rush so let's leave it for now.

**Comment by jseager7** [comment]
I think the discussion has been settled on this issue now, but I was looking at the proposed solution again, and now I'm wondering if it's the best choice.

My proposed solution assumes that the help text is unique to each annotation type:

```pl
$conditions_help_text = $annotation_type_config->{conditions_help_text};
```

But the text that is in the template is already global to every annotation type (or every annotation type that has conditions, since the template controls whether or not the conditions picker is shown):

```html
<div ng-if="showConditions()" class="curs-evidence-conditions">
```

So it seems like it would make more sense to move the configuration property for the help text to somewhere independent of annotation type – otherwise every admin user of Canto (e.g. me) is going to have to set the same configuration value multiple times.

@kimrutherford The question is, if we decide to configure this text globally, where's the best place for its configuration? Based on the existing configuration in `canto.yaml`, the `curs_config` object seems to be the most appropriate, but there's also the `messages` object. Which of these would you prefer? Or would you prefer to add the configuration somewhere else?

**Comment by kimrutherford** [comment]
>  the curs_config object seems to be the most appropriate, but there's also the messages object

Yep, sorry, it's not very consistent.  I think putting to default help text in `curs_config` makes the most sense.

**Comment by jseager7** [comment]
> I think putting to default help text in `curs_config` makes the most sense.

I've done this now. The property is called `experimental_conditions_help_text` and it's a direct child of `curs_config` (didn't make sense to nest it under anything else).

I've also made sure that the annotation edit modal (`annotationEditDialogCtrl`) uses the configurable help text as well, seeing as I forgot to do that in the first commit.

@kimrutherford I'd appreciate some double-checking of the code in `annotationEditDialogCtrl`. I copied the existing conventions with handling promises and the code seems to work, but the existing code seems quite complex so there could be some subtleties I've missed.

If everything looks fine, then this should be ready to merge.

**Comment by kimrutherford** [comment]
> If everything looks fine, then this should be ready to merge.

Thanks James.  It all looks good including the changes in annotationEditDialogCtrl.

**Pull request merged**
