### PR TITLE
Update tag-it source files to latest version

### PR DESCRIPTION
**Pull request by jseager7**
References #2159

This pull request updates the JS and CSS files for tag-it to the latest commit on the tag-it repository (even though that was six years ago).

@kimrutherford I've tested the latest version of the tag-it widget and I can't notice any problems. We can probably merge this and see what happens, but note that there's a possibility this PR could conflict with commit 2f19a53a18d4e1dc561eb07c81c1d1054a7dc06d and PR #2162. Both of those changes contain fixes that are more important than this PR. I haven't had a chance to test this PR with those newer changes merged in yet.

### CODE REVIEW

**Comment by kimrutherford** [comment]
Thanks for giving that a try.  I'll test it when I'm back from my holidays.

**Comment by kimrutherford** [comment]
Hi James.  I've finally tried this PR.  Sorry it took so long.  It all works for me so I think we should merge it.  I tested by merging locally into the master branch.  There are no conflicts.

One thing though, could you tell me about the "destroy" function you've added?  Is it something needed when using the new tag-it version?

**Comment by jseager7** [comment]
> One thing though, could you tell me about the "destroy" function you've added? Is it something needed when using the new tag-it version?

It's been so long I can barely remember, but based on my original comment, it looks like all the changes are just a result of updating the tag-it source files to match what's in the tag-it repository. So it wasn't really me who added the change &ndash; I just pulled the latest changes from another repository.

For what it's worth, here's the commit that adds the `destroy` function in the upstream repository: https://github.com/aehlke/tag-it/commit/bd5bb36e1f86a6def743ec4b88d2ee7a11ea9373

**Comment by kimrutherford** [comment]
> So it wasn't really me who added the change 

Ah yes!  Sorry about that.  I'll merge this now.

**Comment by jseager7** [comment]
I've tested this against the patches applied in https://github.com/pombase/canto/pull/2158/commits/24ae1236875764b44409063ee78fb30719d8f11b and https://github.com/pombase/canto/pull/2162/commits/57bbe92df2224e91675f9ecc1539f59610cabf02, and there don't seem to be any problems introduced by this update (I think the patch in 24ae1236875764b44409063ee78fb30719d8f11b was already merged into the latest version of the tag-it.js repository anyway).

**Pull request merged**
