### PR TITLE
Tidy up the genotype table

### PR DESCRIPTION
**Pull request by kimrutherford**
I've made a branch and pull request for this so I don't misplace the changes I've made.  It's not ready for review or for merging.

### CODE REVIEW

**Comment by kimrutherford** [comment]
I forgot to say these changes are for issue #1955.

**Comment by kimrutherford** [comment]
Hi James.  I've updated this pull request to master.  Could you try it out when you get a chance?  This PR changes (hopefully improves) the like of the genotype table by removing horizontal lines.  As described in #1955.  It also makes the template slightly simpler which is a bonus.

**Comment by jseager7** [comment]
I've tested this locally and there don't seem to be any major problems.

There's the minor issue that the table layout is no longer consistent with what shows on the metagenotype management page (because they don't share directives), which could be slightly confusing for users but nothing serious.

One thing that's different to `master` is that the 'new notes' link (that appears when you've added a note to a genotype) is hidden along with the gene name until you hover over the row. This can lead to a lot of seemingly redundant empty space in some rows:

Not hovered:
image

Hovered:
image

On `master`, the 'new notes' link is always visible, hovered or not:

image

Was this supposed to happen?

**Comment by jseager7** [comment]
One other thing I was wondering, in the interest of saving space, is whether it would be better to have the gene name shown in a popup or tooltip rather than rendered into the row. That way we wouldn't need to have the space constantly reserved just for the event that the user doesn't remember or recognise the gene involved in the genotype.

We could have this popup / tooltip appear when the genotype name is hovered, when the row is hovered, when either are clicked, or we could implement all of those options at once.

This solution would be less suitable if curators often name their genotypes in such a way that it's not clear what the underlying gene is, but I don't know how common that is.

**Comment by kimrutherford** [comment]
> One thing that's different to master is that the 'new notes' link (that appears when you've added a
> note to a genotype) is hidden along with the gene name until you hover over the row.

Thanks for spotting that.  I think it's best it the "new notes" link is always visible.  I'll change it.

> is whether it would be better to have the gene name shown in a popup or tooltip rather than rendered into the row.

Possibly, but the gene name is a link.  So the pop-up would need to have a link in it.

**Comment by jseager7** [comment]
> Possibly, but the gene name is a link. So the pop-up would need to have a link in it.

I guess if we're planning to make the 'new note' button visible again then the excess of blank space might not be as much of an issue. It's probably only worth worrying about this if and when the screen width becomes constrictive, because adding more pop-ups (in addition to the action one we already have) could make the interface look crowded.

**Comment by kimrutherford** [comment]
> I think it's best it the "new notes" link is always visible. I'll change it.

I've fixed that. We end up with quite a bit of white space but I think the table is tidier.

**Comment by kimrutherford** [comment]
I'm going to merge this.  We can fix any problems later.

**Pull request merged**
