### PR TITLE
Include the organism and strain in the metagenotype display name

### PR DESCRIPTION
**Pull request by kimrutherford**
Refs #2156

### CODE REVIEW

**Comment by jseager7** [comment]
Also, if FlyBase uses metagenotypes, how useful is it to show the organism names in their case? Presumably this applies to all forms of metagenotypes, not just pathogen-host interactions.

**Comment by ValWood** [comment]
Just a thought but would it make sense to make this header text appear below the breadcrumb left justified instead of  to the right of the breadcrumb?

**Comment by jseager7** [comment]
> Just a thought but would it make sense to make this header text appear below the breadcrumb left justified instead of to the right of the breadcrumb?

That's an option, although there's a Description section that's not shown in the screenshots above that contains the same information, so having the header text at all seems slightly redundant:

image

So another option is to break that Description section up to describe the constituent parts of the metagenotype, then have a subheading with the metagenotype display name, and finally a generic title to keep the page layout consistent with the rest of Canto.

image

This also has the advantage that we can link to the genotype pages for the constituent genotypes, and italicise the species names.

**Comment by jseager7** [comment]
Although note that we'd probably want to use different terminology from 'pathogen' and 'host' when describing interactions (metagenotypes) that aren't pathogen-host interactions.

**Comment by ValWood** [comment]
I think the reason we haven't done this is that the header is consistent on every page  (genotype/ gene PMID etc),  Although this could still work @kimrutherford 


> Although note that we'd probably want to use different terminology from 'pathogen' and 'host' when describing interactions (metagenotypes) that aren't pathogen-host interactions.

Aren't all  metagenotypes pathogen host interactions though?

**Comment by jseager7** [comment]
> Aren't all metagenotypes pathogen host interactions though?

Perhaps not anymore, since I think the metagenotype concept has been generalised in Canto to cover any multi-organism interaction. This allows the metagenotype to be used as the underlying concept (annotation target) for physical interactions and genetic interactions. In that sense, the pathogen-host interaction is a specialisation of a metagenotype.

So, assuming FlyBase is using physical interactions, genetic interactions, and/or annotations made through the metagenotype management page, any display changes that apply to metagenotypes will have knock-on effects for FlyBase. Having said that, I don't know whether or not FlyBase use the pages that will be affected by this specific change.

If this page was used by FlyBase, they'd probably prefer to see 'Interactor A' and 'Interactor B' instead of 'pathogen' or 'host'. That's the convention followed in the interface for Physical Interactions and Genetic Interactions:

image

**Comment by ValWood** [comment]
Oh I see, pathogen and host would not work here.

**Comment by kimrutherford** [comment]
> Although note that we'd probably want to use different terminology from 'pathogen' and 'host'
> when describing interactions (metagenotypes) that aren't pathogen-host interactions.

I don't think there is a link to get to the metagenotype details page for an interaction so this might not be an immediate problem.

**Comment by jseager7** [comment]
@kimrutherford I've pushed some changes that move the metagenotype display name to a subheading and replace the page title with something shorter and more generic. Here's a screenshot from my local session:

image

The changes to the description section are now in their own issue (#2220), so this is ready to be merged.

**Comment by kimrutherford** [comment]
That's great.  Thanks.

**Pull request merged**
