### PR TITLE
Move jquery to v1.9.1 to fix errors being reported

### PR DESCRIPTION
**Pull request by barnabynorman**
Upgrade and tested all other js scripts and dependencies to highest workable versions
Update include files to load new versions

### CODE REVIEW

**Comment by kimrutherford** [comment]
Unfortunately the update has caused some problems.  The term name autocomplete in the annotation edit popup now throws an error.  That's the dialog you get if you edit an annotation from a table.  Could you try to fix this?  I suspect it's an incompatibility in the newer version of jQuery UI.

Thanks.

annotation-eg-1

------

edit-autocomplete-1


```
angular-v1.5.11.js:14199 TypeError: Cannot set property '_renderItem' of undefined
    at Object.link (http://localhost:7006/static/v910-v1685/js/canto-modules.js:5458:45)
    at http://localhost:7006/static/v910-v1685/js/angular-v1.5.11.js:1259:18
    at http://localhost:7006/static/v910-v1685/js/angular-v1.5.11.js:10146:44
    at invokeLinkFn (http://localhost:7006/static/v910-v1685/js/angular-v1.5.11.js:10152:9)
    at nodeLinkFn (http://localhost:7006/static/v910-v1685/js/angular-v1.5.11.js:9551:11)
    at http://localhost:7006/static/v910-v1685/js/angular-v1.5.11.js:9886:13
    at processQueue (http://localhost:7006/static/v910-v1685/js/angular-v1.5.11.js:16696:28)
    at http://localhost:7006/static/v910-v1685/js/angular-v1.5.11.js:16712:27
    at Scope.$eval (http://localhost:7006/static/v910-v1685/js/angular-v1.5.11.js:17994:28)
    at Scope.$digest (http://localhost:7006/static/v910-v1685/js/angular-v1.5.11.js:17808:31) <span current-term-name="{{annotation.term_name}}" found-callback="termFoundCallback(termId, termName, searchString, matchingSynonym)" annotation-type-name="{{annotationType.name}}">
(anonymous) @ angular-v1.5.11.js:14199
toaster-2.2.0.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by kimrutherford** [comment]
The other problem I've seen is that the font size when auto-completing is a bit too small now.  Could you have a go at fixing that?

Thanks.

autocomplete-small-1

**Comment by barnabynorman** [comment]
It was a mistake going so far forward with the version of jQuery UI - have reverted and tested and seems ok now!
@kimrutherford do you mind testing again and then merging if good?

**Comment by kimrutherford** [comment]
> do you mind testing again and then merging if good?

Thanks!  All fixed.

**Pull request merged**
