### PR TITLE
Support wild-type pathogens in user interface

### PR DESCRIPTION
**Pull request by jseager7**
Closes https://github.com/pombase/canto/issues/2312

This pull request adds support for wild-type pathogen genotypes in metagenotypes, which is needed for the curation of scientific controls in pathogen-host interactions.

@kimrutherford I think I've made all the necessary changes to the front and back end to fix this, but I'd appreciate it if you could double-check the changes to `_metagenotype_store` (in `Curs.pm`).

- - -

Initially, the metagenotype API didn't support storing pathogen taxon IDs or pathogen strains. When trying to store both a wild-type pathogen and a wild-type host, you got a generic error message in the toaster.

I made a bunch of changes to `_metagenotype_store` to handle pathogens the same way as hosts when it came to creating metagenotypes (see 85f40ed93), and now it's possible to create a metagenotype where the pathogen and the host are both wild-type:

image

You can also create a metagenotype with a wild-type pathogen and a mutant host. I'm not sure if this is sensible, but it's easier to leave it enabled than it is to restrict this case.

image

### CODE REVIEW

**Comment by jseager7** [comment]
Note to self: the pathogen genotype column in the annotation table isn't respecting the link disabling logic from https://github.com/pombase/canto/pull/2298. I'll bundle this fix up with this PR if it isn't merged before then.

image

**Comment by jseager7** [comment]
> Note to self: the pathogen genotype column in the annotation table isn't respecting the link disabling logic

This is fixed by https://github.com/pombase/canto/pull/2313/commits/c854e25102a5a14ea80018a794c9e64dade3a196.

**Comment by jseager7** [comment]
Just force-pushed in order to trigger the Travis-CI build again, since it failed for seemingly no reason.

**Comment by kimrutherford** [comment]
> I think I've made all the necessary changes to the front and back end to fix this, but I'd appreciate it if you could
> double-check the changes to _metagenotype_store (in Curs.pm).

Looks good!  It interface works for me and the code changes all look good.  Thanks!

**Pull request merged**
