### PR TITLE
removed nonsense mutation

### PR DESCRIPTION
**Pull request by manulera**

### CODE REVIEW

**Comment by manulera** [comment]
Actually don't merge yet. Updating docs

**Comment by manulera** [comment]
This one should be ok, it includes the docs

**Comment by kimrutherford** [comment]
> what about existing entries in JaponicusDB? Should we also change the allele type at their chado?

I'll check to see if there are any nonsense_mutation alleles in JaponicusDB.  I suspect not.

We'll also need to change the existing `nonsense_mutation` alleles in Canto to be `partial_amino_acid_deletion`.  And this in-progress PHAF file needs changing too:
`pombe_embl/external_data/phaf_files/in-progress/PMID_24362309_multigene_alleles.tsv`

**Comment by manulera** [comment]
> We'll also need to change the existing nonsense_mutation alleles in Canto to be partial_amino_acid_deletion. 

There is a file with all of them that I made, but forgot to add to the list of changes that needed to be applied:

https://github.com/pombase/allele_qc/blob/master/manual_fixes_pombase/allele_manual_changes_formatted.tsv

**Comment by kimrutherford** [comment]
> There is a file with all of them that I made, but forgot to add to the list of changes that needed to be applied:

Hi @manulera 

I queried the Canto database and found these alleles with type "nonsense_mutation".  There is also an unnamed nonsense_mutation.

```
alg10-183-stop
apm1-1
atg7-m1
bro1-E644STOP
caf4-Q470stop
caf4-R530stop
ctf1 Tyr260Stop
cut12-1
cut2-R267->stop
dnm1-G148stop
dot2-439
dri1-W46X
dsc2-V160*
ekc1-W636->stop
elf1-21
erh1-Q46->stop
fis1-E128stop
hhp2-W214->stop
lcf1-W376->stop
mcl1-1
not2-E31STOP
nup184-1
osh6-S117STOP
pan2-Q69Stop
pcs2-N147D
pds5-G755V-STOP
pds5-K686-STOP
pli1-Q196->stop
pli1-Q8->stop
pli1-Y108->stop
pmr1-R155->stop
pmr1-W880->stop
ppe1-E35->stop
ppk14-R148STOP
psc3-303
pst1-1
puf2-Q40STOP
puf2-Y416STOP
rad23-1
rqh1-h2
sck1-Q112->stop
sgf11-Q64->stop
slr9-1
SPAC1296.01c-Q175STOP
spo3-KC51
sre1-Q802*
sst4-Q202STOP
sst4-W170STOP
sst6-Q207STOP
ssu72-Gln57Stop
sty1-791
tht1-D543*
tor1-g2
tsc1-Q688STOP
tsc2-L636STOP
tsn1-S204stop
tsn1-Y227stop
ucp7-310
ufd1-I210HRLstop
vps25-W113STOP
wee1-112
wis1-887
```

**Comment by manulera** [comment]
Oh, I see, so the ones in that file are already fixed, actually. I will move it to the log. Let me have a go at those.

**Comment by kimrutherford** [comment]
> Let me have a go at those.

Maybe it's easier for me to change them directly in the Canto database?

**Pull request merged**
