### PR TITLE
Small improvements to genotype row actions

### PR DESCRIPTION
**Pull request by jseager7**
Related: #1945 

This pull request changes the actions popup on genotype tables, specifically:

* increases the font size to match Canto's table data; and

* reorders the actions in the list so that the more frequently-used actions are closer to the top.

image

@ValWood I've followed your suggestion to place 'Copy and Edit' and 'Edit' as the second and third items in the list (respectively); for the rest of the items their ordering is unchanged, relatively speaking.

This change will affect all versions of Canto, so @mah11 @vmt25 are you happy with these changes, or would you prefer any other changes to the ordering of the actions list? I know there's a few actions not shown in the screenshot that are used by FlyBase (e.g. genotype notes).

(Note that PomBase isn't tracking the `master` branch of Canto, so even if these changes are merged, they might not appear on PomBase's Canto immediately.)

### CODE REVIEW

**Comment by kimrutherford** [comment]
Hi James.  Sorry I haven't commented on this.  I think you should go ahead and merge the change.  We can tweak things later if needed.

**Comment by kimrutherford** [comment]
> I think you should go ahead and merge the change.

Although I've only just noticed that there are conflicts.  Do you think that's easy to fix?

**Comment by jseager7** [comment]
> Although I've only just noticed that there are conflicts. Do you think that's easy to fix?

I'll take a look. It's probably just because of extra items being added to the actions list in the meantime.

**Comment by jseager7** [comment]
I've fixed the merge conflict. Here's how the list looks now, with the new 'View/edit notes' action enabled:

image

I also fixed a weird bug where the 'Add/edit background' link was being shown twice.

**Review by kimrutherford — APPROVED** [review]
Thanks James.  I think this can be merged.

**Pull request merged**
