### PR TITLE
Change metagenotype table to handle interactions

### PR DESCRIPTION
**Pull request by kimrutherford**
Hi James.  Another week, another schema change.  :-)

To implement #1891,I'm suggesting the we make the metagenotype table more general by renaming the pathogen_genotype_id and host_genotype_id columns.  And by adding a "type" column the type would be constrained to "pathogen-host" or "interaction" (see https://github.com/pombase/canto/blob/tickets/ticket-1891/etc/curs.sql#L77).

For #1891 we need to store a genotype to genotype interaction in the database and then connect that to phenotype term and an evidence code.  I'd prefer to re-used the metagenotype table to hold these interactions and to reuse as much metagenotype code as possible.

I'm not planning to merge this pull request yet but I wanted to make a PR for discussion.  I'm going to try implementing the basics of the interaction interface before I think about merging to make sure that these changes make sense.

### CODE REVIEW

**Comment by jseager7** [comment]
While I agree with the idea of generalising a metagenotype to cover organisms in any role (not just pathogen and host), I'm slightly concerned about how generalising this might harm the readability of the front-end code, in the sense that it could make it more difficult to reason about which organism is the pathogen and which is the host when working on the view model, and so on.

This is important in the case of PHI-Canto, since generally the pathogen data should be displayed 'first', meaning further to the left than the host data.

I don't know what the naming conventions are going to be, but I guess we could come up with some sort of de-facto mapping that `genotype_a` is the pathogen and `genotype_b` is the host. It might not be a problem in practice, and I'm not sure of a good way to solve this issue yet anyway. Maybe it will be more apparent once the code is changed.

**Comment by jseager7** [comment]
As for the changes required, there is at least some code that is using dynamic naming based on things like the organism type, for example:

```js
$scope.getOrganismName = function (type) {
        var metagenotype = $scope.metagenotype[type + '_genotype'];
        var name = metagenotype.organism.full_name || '';
        return name;
      };
```
Anything like this will need changing, but I think the general solution is better since hopefully we can avoid having to account so much for domain-specific naming in the code.

**Comment by kimrutherford** [comment]
> As for the changes required, there is at least some code that is using dynamic naming based on things
> like the organism type, for example:

Thanks for that example.  I hadn't thought about that case.  I'll do a thorough check of the JS code before we merge the changes.

**Comment by kimrutherford** [comment]
> I'm slightly concerned about how generalising this might harm the readability of the front-end code

I'm hoping we won't need to change any of the current front end code.  The Perl webservices can continue to accept the same requests and return the same responses in the PHI case.  Because we'll have a "type" field in the metagenotype table the server code will always know if the metagenotype it's looking at is a pathogen-host or genotype-genotype interaction.

So now I've thought about it hopefully this won't be a problem:
> As for the changes required, there is at least some code that is using dynamic naming based on
> things like the organism type, for example:

**Comment by jseager7** [comment]
> Because we'll have a "type" field in the metagenotype table the server code will always know if the metagenotype it's looking at is a pathogen-host or genotype-genotype interaction.

Now that I've actually bothered to read the issue, I realise that the view logic for these two cases of interaction has almost nothing in common, and really the only thing we're abstracting is the data layer. In that case, I think you're right about the case of not needing many front-end changes.

My only concern was whether these two cases will have some logic in common at the controller or service level. The `Metagenotype` service doesn't seem to make any assumptions as far as I can tell, so that should be fine. Maybe the only issue is the components used on the PHI-Canto Metagenotype Management page (like `metagenotypeListRow` and so on) &ndash; right now they only cover the pathogen-host case. I think it would be better to either:

* rename these components to make their pathogen-host functionality explicit, since they are currently not general enough to handle all types of metagenotype; or

* generalise the controllers to handle any type of genotype, and make the domain-specific labelling configurable (or, alternatively, assign their templates dynamically).

This is presuming you'd ever want a way in FlyBase to list the metagenotypes in a table, in the same way as is done with PHI-Canto. If that's not likely, then we can probably get away with not even renaming the components.

**Comment by kimrutherford** [comment]
>The Perl webservices can continue to accept the same requests and return the same responses
> in the PHI case. 

I forgot that I've done some of that already.  Because of this change, creating new metagenotypes works after the schema update:

https://github.com/pombase/canto/commit/b549481c17cae4d2bd56f4f248594002a8159dad#diff-a214cd50f78d3efb2cddc1729a1cba53R502

Creating a PHI metagenotype annotation still works.  And the aliases here mean that the metagenotype annotations display correctly:
https://github.com/pombase/canto/commit/b549481c17cae4d2bd56f4f248594002a8159dad#diff-acd857e045721043ff88245ce36d6b88R162

Some of the server code still assumes that all the entries in the metagenotype tables are pathogen-host interactions.  I'll fix that before we merge.

**Comment by jseager7** [comment]
I'm going to push any simple fixes to this pull request instead of opening issues. I've just fixed an error in commit 9c82ec7, in the case where there's only one organism on the pathogen or host genotype management pages.

**Comment by jseager7** [comment]
Another thing I've noticed is that the 'Quick links' section is being shown permanently now, even when I'm not in advanced mode. All it shows is a link to physical interaction, though. Not sure if this is just something that's been enabled as a convenience for development?

image

**Comment by kimrutherford** [comment]
> Another thing I've noticed is that the 'Quick links' section is being shown permanently now,
> even when I'm not in advanced mode. All it shows is a link to physical interaction, though. Not
> sure if this is just something that's been enabled as a convenience for development?

It's sort-of for development. But I also wanted to see if the curators were interested in having a quick link to make an interaction rather than navigating to a genotype details page first.

>  I haven't been able to test the genetic interaction workflow myself, because I'm not sure how to enable it.

There isn't a long workflow for interactions any more, we can only create interactions via the dialog: https://github.com/pombase/canto/issues/1380

**Comment by jseager7** [comment]
> I haven't been able to test the genetic interaction workflow myself, because I'm not sure how to enable it.

I've just remembered that I didn't have genetic interaction enabled in the `canto_deploy` file, so that will be why I couldn't see it. We disabled it for PHI-base a long time ago because nobody in the team thought we'd need it.

**Comment by kimrutherford** [comment]
Thanks very much for testing and for the fixes.  I'll do more testing too before merging.  It will be a while before I do that as I need to fix things so that we can store an interaction without a phenotype.  Currently a phenotype is required.

Also I need to write the code to convert old gene-gene interactions in to genotype-genotype interactions when the database is upgraded.  And for PomBase pombase/pombase-chado#739 and pombase/website#1348 need to be done.  It will take a while!

I've been rebasing this branch occasionally so that the final merge won't be too painful.

**Comment by ValWood** [comment]
I haven't seen any genetic interactions yet.

As we were working on the new geentic interactions interface we were thinking how much that traditional genetic interactions have in common with multi-organism phenotypes.

It is likely that  both interfaces could benefit from input from the workflow of the other, but I haven't been able to  pull this apart in my head yet , and we have a good working solution for both.

Because researchers in the pathogen community are  usually concentrating on the inter-organism interactions they don't tend to look at "within species genetic interactions". It could be enabled later if required.

**Comment by kimrutherford** [comment]
Hi James.

I'm closing to close this pull request because it's getting out of hand and the branch name doesn't make sense any more.  I've made a new branch (https://github.com/pombase/canto/tree/genotype-interactions) that contains the schema change and all the other changes that depend on it.

**Pull request closed without merging**
